// This file is @generated by prost-build.
#[derive(
    ::prost_canonical_serde::CanonicalSerialize,
    ::prost_canonical_serde::CanonicalDeserialize
)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NameConflicts {
    #[prost(string, tag = "1")]
    #[prost_canonical_serde(proto_name = "key", json_name = "key")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    #[prost_canonical_serde(proto_name = "value", json_name = "value")]
    pub value: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    #[prost_canonical_serde(proto_name = "map", json_name = "map")]
    pub map: i32,
    #[prost(oneof = "name_conflicts::Choice", tags = "4, 5")]
    pub choice: ::core::option::Option<name_conflicts::Choice>,
}
/// Nested message and enum types in `NameConflicts`.
pub mod name_conflicts {
    #[derive(
        ::prost_canonical_serde::CanonicalSerialize,
        ::prost_canonical_serde::CanonicalDeserialize
    )]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Choice {
        #[prost(string, tag = "4")]
        #[prost_canonical_serde(proto_name = "key_choice", json_name = "keyChoice")]
        KeyChoice(::prost::alloc::string::String),
        #[prost(int32, tag = "5")]
        #[prost_canonical_serde(proto_name = "value_choice", json_name = "valueChoice")]
        ValueChoice(i32),
    }
}
