// This file is @generated by prost-build.
#[derive(
    ::prost_canonical_serde::CanonicalSerialize,
    ::prost_canonical_serde::CanonicalDeserialize
)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Example {
    #[prost(string, tag = "1")]
    #[prost_canonical_serde(proto_name = "name", json_name = "name")]
    pub name: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    #[prost_canonical_serde(proto_name = "count", json_name = "count")]
    pub count: i64,
    #[prost(bytes = "vec", tag = "3")]
    #[prost_canonical_serde(proto_name = "payload", json_name = "payload")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "4")]
    #[prost_canonical_serde(proto_name = "created_at", json_name = "createdAt")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
}
