// This file is @generated by prost-build.
#[derive(
    ::prost_canonical_serde::CanonicalSerialize,
    ::prost_canonical_serde::CanonicalDeserialize
)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Nested {
    #[prost(int32, tag = "1")]
    #[prost_canonical_serde(proto_name = "id", json_name = "id")]
    pub id: i32,
    #[prost(string, tag = "2")]
    #[prost_canonical_serde(proto_name = "note", json_name = "note")]
    pub note: ::prost::alloc::string::String,
}
#[derive(
    ::prost_canonical_serde::CanonicalSerialize,
    ::prost_canonical_serde::CanonicalDeserialize
)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KitchenSink {
    #[prost(int32, tag = "1")]
    #[prost_canonical_serde(proto_name = "int32_field", json_name = "int32Field")]
    pub int32_field: i32,
    #[prost(int64, tag = "2")]
    #[prost_canonical_serde(proto_name = "int64_field", json_name = "int64Field")]
    pub int64_field: i64,
    #[prost(uint64, tag = "3")]
    #[prost_canonical_serde(proto_name = "uint64_field", json_name = "uint64Field")]
    pub uint64_field: u64,
    #[prost(bool, tag = "4")]
    #[prost_canonical_serde(proto_name = "bool_field", json_name = "boolField")]
    pub bool_field: bool,
    #[prost(string, tag = "5")]
    #[prost_canonical_serde(proto_name = "string_field", json_name = "stringField")]
    pub string_field: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "6")]
    #[prost_canonical_serde(proto_name = "bytes_field", json_name = "bytesField")]
    pub bytes_field: ::prost::alloc::vec::Vec<u8>,
    #[prost(float, tag = "7")]
    #[prost_canonical_serde(proto_name = "float_field", json_name = "floatField")]
    pub float_field: f32,
    #[prost(double, tag = "8")]
    #[prost_canonical_serde(proto_name = "double_field", json_name = "doubleField")]
    pub double_field: f64,
    #[prost(enumeration = "Status", tag = "9")]
    #[prost_canonical_serde(proto_name = "status", json_name = "status")]
    pub status: i32,
    #[prost(message, optional, tag = "10")]
    #[prost_canonical_serde(proto_name = "nested", json_name = "nested")]
    pub nested: ::core::option::Option<Nested>,
    #[prost(message, repeated, tag = "11")]
    #[prost_canonical_serde(
        proto_name = "repeated_nested",
        json_name = "repeatedNested"
    )]
    pub repeated_nested: ::prost::alloc::vec::Vec<Nested>,
    #[prost(map = "string, int32", tag = "12")]
    #[prost_canonical_serde(proto_name = "string_to_int", json_name = "stringToInt")]
    pub string_to_int: ::std::collections::HashMap<::prost::alloc::string::String, i32>,
    #[prost(map = "int32, string", tag = "13")]
    #[prost_canonical_serde(proto_name = "int_to_string", json_name = "intToString")]
    pub int_to_string: ::std::collections::HashMap<i32, ::prost::alloc::string::String>,
    #[prost(message, optional, tag = "16")]
    #[prost_canonical_serde(proto_name = "timestamp", json_name = "timestamp")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(int32, optional, tag = "17")]
    #[prost_canonical_serde(proto_name = "optional_int32", json_name = "optionalInt32")]
    pub optional_int32: ::core::option::Option<i32>,
    #[prost(oneof = "kitchen_sink::Choice", tags = "14, 15")]
    pub choice: ::core::option::Option<kitchen_sink::Choice>,
}
/// Nested message and enum types in `KitchenSink`.
pub mod kitchen_sink {
    #[derive(
        ::prost_canonical_serde::CanonicalSerialize,
        ::prost_canonical_serde::CanonicalDeserialize
    )]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Choice {
        #[prost(string, tag = "14")]
        #[prost_canonical_serde(proto_name = "name", json_name = "name")]
        Name(::prost::alloc::string::String),
        #[prost(message, tag = "15")]
        #[prost_canonical_serde(
            proto_name = "nested_choice",
            json_name = "nestedChoice"
        )]
        NestedChoice(super::Nested),
    }
}
#[derive(
    ::prost_canonical_serde::CanonicalSerialize,
    ::prost_canonical_serde::CanonicalDeserialize
)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Status {
    Unspecified = 0,
    Active = 1,
    Suspended = 2,
}
impl Status {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "STATUS_UNSPECIFIED",
            Self::Active => "STATUS_ACTIVE",
            Self::Suspended => "STATUS_SUSPENDED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "STATUS_ACTIVE" => Some(Self::Active),
            "STATUS_SUSPENDED" => Some(Self::Suspended),
            _ => None,
        }
    }
}
